"""
Delivery service.

Responsible for sending clinical output to the practice after a form submission.

This module defines:
  - DeliveryService: abstract base class
  - EmailDeliveryService: production SMTP implementation
  - ConsoleDeliveryService: local development only — logs to stdout, never sends email

Architecture rules:
  - This module must never access the database.
  - This module must never import clinical engine modules or clinical contracts.
  - This module must never retry on failure.
  - This module must never update delivery status (that is the router's responsibility).
  - This module must never generate PDFs (that is the caller's responsibility).

The PDF attachment is the sole carrier of clinical detail. The email body is a
short static message directing the recipient to open the attachment. This module
has no knowledge of patient details, answers, or clinical content.

PDF generation is a submission-time concern, not a delivery concern. The caller
(form_router.py) generates the PDF once at submission time and passes the
pre-rendered bytes to send_clinical_output. This separation makes retry viable:
the same bytes are sent on every attempt without regeneration.

Configuration (EmailDeliveryService):
    SMTP_HOST, SMTP_PORT (default 587), SMTP_USER, SMTP_PASSWORD,
    EMAIL_FROM, SMTP_TIMEOUT (default 30)

ConsoleDeliveryService is for local development only. Never instantiate in production.
"""

import logging
import os
import smtplib
from abc import ABC, abstractmethod
from datetime import datetime
from email.message import EmailMessage

logger = logging.getLogger(__name__)


class EmailDeliveryError(Exception):
    pass


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------

class DeliveryService(ABC):
    @abstractmethod
    def send_clinical_output(
        self,
        to_email: str,
        condition_label: str,
        pdf_bytes: bytes,
        submission_id: str,
        submitted_at: datetime,
    ) -> None: ...


# ---------------------------------------------------------------------------
# Email body (static — no clinical content)
# ---------------------------------------------------------------------------

def _format_body(
    condition_label: str,
    submission_id: str,
    submitted_at: datetime,
) -> str:
    return "\n".join([
        "E-CONSULTATION SUBMISSION",
        "",
        f"Submission ID: {submission_id}",
        f"Condition: {condition_label}",
        f"Submitted at: {submitted_at.strftime('%Y-%m-%d %H:%M:%S')} UTC",
        "",
        "Please open the attached PDF for the full submission.",
        "",
        "This message was generated automatically by the e-consultation system.",
        "Do not reply to this email.",
    ])


# ---------------------------------------------------------------------------
# Production implementation
# ---------------------------------------------------------------------------

class EmailDeliveryService(DeliveryService):
    """
    Sends clinical output via SMTP with a PDF attachment.

    SMTP configuration is read from environment variables at instantiation time.
    A missing variable will raise RuntimeError at startup, not silently at send time.

    PDF bytes are generated by the caller (form_router.py) at submission time
    and passed in pre-rendered. This service does not generate PDFs.

    The email body is a static message with submission metadata only. All clinical
    detail is in the PDF attachment.
    """

    def __init__(self) -> None:
        self._smtp_host = self._require_env("SMTP_HOST")
        self._smtp_port = int(os.environ.get("SMTP_PORT", "587"))
        self._smtp_user = self._require_env("SMTP_USER")
        self._smtp_password = self._require_env("SMTP_PASSWORD")
        self._email_from = self._require_env("EMAIL_FROM")
        self._smtp_timeout = int(os.environ.get("SMTP_TIMEOUT", "30"))

    @staticmethod
    def _require_env(name: str) -> str:
        value = os.environ.get(name)
        if not value:
            raise RuntimeError(
                f"EmailDeliveryService requires environment variable: {name}"
            )
        return value

    def send_clinical_output(
        self,
        to_email: str,
        condition_label: str,
        pdf_bytes: bytes,
        submission_id: str,
        submitted_at: datetime,
    ) -> None:
        subject = f"E-consultation: {condition_label} [{submission_id}]"
        body = _format_body(condition_label, submission_id, submitted_at)

        pdf_filename = (
            f"econsultation_{submitted_at.strftime('%Y-%m-%d')}_{submission_id[:8]}.pdf"
        )

        msg = EmailMessage()
        msg["Subject"] = subject
        msg["From"] = self._email_from
        msg["To"] = to_email
        msg.set_content(body)
        msg.add_attachment(
            pdf_bytes,
            maintype="application",
            subtype="pdf",
            filename=pdf_filename,
        )

        try:
            with smtplib.SMTP(self._smtp_host, self._smtp_port, timeout=self._smtp_timeout) as server:
                server.ehlo()
                server.starttls()
                server.ehlo()
                server.login(self._smtp_user, self._smtp_password)
                server.send_message(msg)
        except Exception as e:
            raise EmailDeliveryError(str(e)) from e


# ---------------------------------------------------------------------------
# Development implementation
# ConsoleDeliveryService is for local development only. Never instantiate in production.
# ---------------------------------------------------------------------------

class ConsoleDeliveryService(DeliveryService):
    """
    Logs clinical output to stdout instead of sending email.

    For local development only. Raises RuntimeError if DEV_MODE is not set,
    to prevent accidental use in production.

    PDF bytes are generated by the caller (form_router.py) at submission time
    and passed in pre-rendered. This service logs the byte count but does not
    generate or modify the PDF.

    The email body is a static message with submission metadata only, matching
    the production implementation.
    """

    def __init__(self) -> None:
        if os.environ.get("DEV_MODE", "").lower() not in ("1", "true"):
            raise RuntimeError(
                "ConsoleDeliveryService may only be instantiated when DEV_MODE=1. "
                "Use EmailDeliveryService in production."
            )

    def send_clinical_output(
        self,
        to_email: str,
        condition_label: str,
        pdf_bytes: bytes,
        submission_id: str,
        submitted_at: datetime,
    ) -> None:
        body = _format_body(condition_label, submission_id, submitted_at)

        logger.info(
            "[DEV_MODE] Email send skipped. Would have sent:\n"
            "  To:      %s\n"
            "  Subject: E-consultation: %s [%s]\n"
            "  PDF:     %d bytes\n"
            "  Body:\n%s",
            to_email,
            condition_label,
            submission_id,
            len(pdf_bytes),
            "\n".join(f"    {line}" for line in body.splitlines()),
        )