version: 2
updates:
  # Maintain Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]
      - dependency-name: "psycopg2-binary"
        update-types: ["version-update:semver-major"]
      - dependency-name: "nh3"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
