"""
Delivery service.

Responsible for sending clinical output to the practice after a form submission.

This module defines:
  - DeliveryService: abstract base class
  - EmailDeliveryService: production SMTP implementation
  - MailgunHttpDeliveryService: production Mailgun HTTP API implementation

Architecture rules:
  - This module must never access the database.
  - This module must never import clinical engine modules or clinical contracts.
  - This module must never retry on failure.
  - This module must never update delivery status (that is the router's responsibility).
  - This module must never generate PDFs (that is the caller's responsibility).

The PDF attachment is the sole carrier of clinical detail. The email body is a
short static message directing the recipient to open the attachment. This module
has no knowledge of patient details, answers, or clinical content.

PDF generation is a submission-time concern, not a delivery concern. The caller
(form_router.py) generates the PDF once at submission time and passes the
pre-rendered bytes to send_clinical_output. This separation makes retry viable:
the same bytes are sent on every attempt without regeneration.

Return value of send_clinical_output:
  - MailgunHttpDeliveryService returns the provider message ID string (the
    Mailgun message ID with angle brackets stripped). The delivery worker
    persists this immediately so the webhook router can match incoming signals.
  - EmailDeliveryService returns None. SMTP does not support webhooks; the
    delivery worker takes the legacy 'sent' path when None is returned.

Configuration (EmailDeliveryService):
    SMTP_HOST, SMTP_PORT (default 587), SMTP_USER, SMTP_PASSWORD,
    EMAIL_FROM, SMTP_TIMEOUT (default 30)

Configuration (MailgunHttpDeliveryService):
    MAILGUN_API_KEY, MAILGUN_DOMAIN, EMAIL_FROM

Service selection (main.py):
    If MAILGUN_API_KEY is set, MailgunHttpDeliveryService is used.
    Otherwise EmailDeliveryService (SMTP) is used.
"""

import logging
import os
import smtplib
from abc import ABC, abstractmethod
from datetime import datetime
from email.message import EmailMessage

import requests

logger = logging.getLogger(__name__)

_MAILGUN_EU_API_BASE = "https://api.eu.mailgun.net/v3"


class EmailDeliveryError(Exception):
    pass


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------

class DeliveryService(ABC):
    @abstractmethod
    def send_clinical_output(
        self,
        to_email: str,
        condition_label: str,
        pdf_bytes: bytes,
        submission_id: str,
        submitted_at: datetime,
    ) -> str | None: ...


# ---------------------------------------------------------------------------
# Email body (static — no clinical content)
# ---------------------------------------------------------------------------

def _format_body(
    condition_label: str,
    submission_id: str,
    submitted_at: datetime,
) -> str:
    return "\n".join([
        "E-CONSULTATION SUBMISSION",
        "",
        f"Submission ID: {submission_id}",
        f"Condition: {condition_label}",
        f"Submitted at: {submitted_at.strftime('%Y-%m-%d %H:%M:%S')} UTC",
        "",
        "Please open the attached PDF for the full submission.",
        "",
        "This message was generated automatically by the e-consultation system.",
        "Do not reply to this email.",
    ])


# ---------------------------------------------------------------------------
# SMTP implementation
# ---------------------------------------------------------------------------

class EmailDeliveryService(DeliveryService):
    """
    Sends clinical output via SMTP with a PDF attachment.

    SMTP configuration is read from environment variables at instantiation time.
    A missing variable will raise RuntimeError at startup, not silently at send time.

    PDF bytes are generated by the caller (form_router.py) at submission time
    and passed in pre-rendered. This service does not generate PDFs.

    The email body is a static message with submission metadata only. All clinical
    detail is in the PDF attachment.

    Returns None. SMTP does not support webhooks; the delivery worker takes the
    legacy 'sent' path when None is returned.
    """

    def __init__(self) -> None:
        self._smtp_host = self._require_env("SMTP_HOST")
        self._smtp_port = int(os.environ.get("SMTP_PORT", "587"))
        self._smtp_user = self._require_env("SMTP_USER")
        self._smtp_password = self._require_env("SMTP_PASSWORD")
        self._email_from = self._require_env("EMAIL_FROM")
        self._smtp_timeout = int(os.environ.get("SMTP_TIMEOUT", "30"))

    @staticmethod
    def _require_env(name: str) -> str:
        value = os.environ.get(name)
        if not value:
            raise RuntimeError(
                f"EmailDeliveryService requires environment variable: {name}"
            )
        return value

    def send_clinical_output(
        self,
        to_email: str,
        condition_label: str,
        pdf_bytes: bytes,
        submission_id: str,
        submitted_at: datetime,
    ) -> str | None:
        subject = f"E-consultation: {condition_label} [{submission_id}]"
        body = _format_body(condition_label, submission_id, submitted_at)

        pdf_filename = (
            f"econsultation_{submitted_at.strftime('%Y-%m-%d')}_{submission_id[:8]}.pdf"
        )

        msg = EmailMessage()
        msg["Subject"] = subject
        msg["From"] = self._email_from
        msg["To"] = to_email
        msg.set_content(body)
        msg.add_attachment(
            pdf_bytes,
            maintype="application",
            subtype="pdf",
            filename=pdf_filename,
        )

        try:
            with smtplib.SMTP(self._smtp_host, self._smtp_port, timeout=self._smtp_timeout) as server:
                server.ehlo()
                server.starttls()
                server.ehlo()
                server.login(self._smtp_user, self._smtp_password)
                server.send_message(msg)
        except Exception as e:
            raise EmailDeliveryError(str(e)) from e

        return None


# ---------------------------------------------------------------------------
# Mailgun HTTP API implementation
# ---------------------------------------------------------------------------

class MailgunHttpDeliveryService(DeliveryService):
    """
    Sends clinical output via the Mailgun HTTP API with a PDF attachment.

    Uses the EU regional endpoint. Configuration is read from environment
    variables at instantiation time. A missing variable raises RuntimeError
    at startup, not silently at send time.

    This implementation exists because Railway's free and hobby plans block
    outbound SMTP connections. The HTTP API is the recommended alternative.

    PDF bytes are generated by the caller at submission time and passed in
    pre-rendered. This service does not generate PDFs.

    The email body is a static message with submission metadata only. All
    clinical detail is in the PDF attachment.

    Returns the Mailgun message ID string with angle brackets stripped, e.g.:
        "20260423123456.1.xyz@mailgun.org"
    The delivery worker persists this immediately after a successful send so
    the webhook router can match incoming delivery signals to the correct job.
    """

    def __init__(self) -> None:
        self._api_key = self._require_env("MAILGUN_API_KEY")
        self._domain = self._require_env("MAILGUN_DOMAIN")
        self._email_from = self._require_env("EMAIL_FROM")

    @staticmethod
    def _require_env(name: str) -> str:
        value = os.environ.get(name)
        if not value:
            raise RuntimeError(
                f"MailgunHttpDeliveryService requires environment variable: {name}"
            )
        return value

    def send_clinical_output(
        self,
        to_email: str,
        condition_label: str,
        pdf_bytes: bytes,
        submission_id: str,
        submitted_at: datetime,
    ) -> str | None:
        subject = f"E-consultation: {condition_label} [{submission_id}]"
        body = _format_body(condition_label, submission_id, submitted_at)

        pdf_filename = (
            f"econsultation_{submitted_at.strftime('%Y-%m-%d')}_{submission_id[:8]}.pdf"
        )

        url = f"{_MAILGUN_EU_API_BASE}/{self._domain}/messages"

        try:
            response = requests.post(
                url,
                auth=("api", self._api_key),
                data={
                    "from": self._email_from,
                    "to": to_email,
                    "subject": subject,
                    "text": body,
                },
                files={
                    "attachment": (pdf_filename, pdf_bytes, "application/pdf"),
                },
                timeout=30,
            )
            response.raise_for_status()
        except requests.RequestException as e:
            raise EmailDeliveryError(str(e)) from e

        # Parse and return the Mailgun message ID. Strip angle brackets if
        # present so the stored value is a clean string for DB lookups:
        # Mailgun returns: {"id": "<20260423123456.1.xyz@mailgun.org>", ...}
        raw_id = response.json().get("id", "")
        return raw_id.strip("<>")